Copy source to builder container as user rust
Otherwise we can't override `Cargo.lock` during the build process:
```
Sending build context to Docker daemon  5.045MB
Step 1/8 : FROM ekidd/rust-musl-builder:1.24.0
 ---> 83a42419ac94
Step 2/8 : ADD cobalt.rs/ /home/rust/src
 ---> Using cache
 ---> 49abf11335df
Step 3/8 : RUN cargo build --release
 ---> Running in 349c904720cc
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to write /home/rust/src/Cargo.lock

Caused by:
  failed to open: /home/rust/src/Cargo.lock

Caused by:
  Permission denied (os error 13)
The command '/bin/sh -c cargo build --release' returned a non-zero code: 101
```